# render.yaml - for Streamline Backend FastAPI Deployment
services:
  - type: web
    name: streamline-recommender-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    runtime: python
    autoDeploy: true
    rootDir: backend

    envVars:
      - key: ENV
        value: production

    buildFilter:
      includedPaths:
        - backend/**
        - data/product_metadata.json
        - data/beauty_product_ratings.csv
        - requirements.txt
      ignoredPaths:
        - frontend/**
        - README.md
        - .gitignore
        - .env

    healthCheckPath: "/recommend/"
    preDeployCommand: "echo Running any DB migrations or static setup if needed"

    secretFiles:
      - name: .env
        mountPath: ./
        contents: |
          SECRET_KEY=your-secret-key
          DEBUG=False
