services:
  - type: web
    name: streamline-fastapi
    runtime: python
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
